In [1]:
import pandas as pd

emp_df = pd.read_csv("/content/employees.csv")

In [2]:
emp_df.describe()

              Age  Years Of Experience        Salary
count  320.000000           320.000000    320.000000
mean    31.587500             7.687500  10175.000000
std      4.607323             4.428729   2615.483196
min     23.000000             1.000000   5500.000000
25%     28.000000             4.000000   8000.000000
50%     32.000000             7.500000  10000.000000
75%     35.000000            12.000000  12000.000000
max     41.000000            15.000000  17000.000000

In [3]:
emp_df.head(10)

,First Name,Last Name,Email,Phone,Gender,Age,Job Title,Years Of Experience,Salary,Department
0,Jose,Lopez,joselopez0944@slingacademy.com,+1-971-533-4552x1542,male,25,Project Manager,1,8500,Product
1,Diane,Carter,dianecarter1228@slingacademy.com,881.633.0107,female,26,Machine Learning Engineer,2,7000,Product
2,Shawn,Foster,shawnfoster2695@slingacademy.com,001-966-861-0065x493,male,37,Project Manager,14,17000,Product
3,Brenda,Fisher,brendafisher3185@slingacademy.com,001-574-564-4648,female,31,Web Developer,8,10000,Product
4,Sean,Hunter,seanhunter4753@slingacademy.com,5838355842,male,35,Project Manager,11,14500,Product
5,Joshua,Jacobs,joshuajacobs5904@slingacademy.com,053-913-2609,male,28,Project Manager,3,10500,Product
6,Brianna,Marshall,briannamarshall6438@slingacademy.com,701-932-8553,female,33,Machine Learning Engineer,10,11000,Product
7,John,Tate,johntate7881@slingacademy.com,001-889-992-5260x62725,male,33,Mobile Developer,10,11000,Product
8,Jillian,Byrd,jillianbyrd8170@slingacademy.com,077-635-0084x1647,female,34,Web Developer,10,11000,Product
9,Melanie,Sharp,melaniesharp9256@slingacademy.com,(848)212-0230,female,41,Web Developer,15,14500,Product

In [5]:
!pip install faker

Collecting faker
  Downloading faker-37.3.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)
Downloading faker-37.3.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 22.6 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-37.3.0

In [8]:
import pandas as pd
import random
import numpy as np
from faker import Faker

fake = Faker()
Faker.seed(42)
np.random.seed(42)

emp_df = pd.read_csv("employees.csv")
original_columns = emp_df.columns.tolist()

num_employees = 10000
languages = ["Spanish", "Mandarin", "Hindi", "French", "Korean", "Tagalog", "German", "Russian"]

h1b_country_dist = {
    "India": 0.72,
    "China": 0.13,
    "Canada": 0.05,
    "South Korea": 0.03,
    "Philippines": 0.03,
    "Taiwan": 0.02,
    "Mexico": 0.02
}

department_distribution = {
    "Legal": 0.05,
    "Marketing": 0.10,
    "Administrative": 0.10,
    "Operations": 0.20,
    "Sales": 0.10,
    "Finance": 0.05,
    "I/T": 0.10,
    "Product": 0.20,
    "Human Resource": 0.10
}

salary_ranges = {
    "Legal": (90000, 130000),
    "Marketing": (60000, 85000),
    "Administrative": (40000, 60000),
    "Operations": (50000, 75000),
    "Sales": (55000, 90000),
    "Finance": (70000, 110000),
    "I/T": (80000, 120000),
    "Product": (90000, 130000),
    "Human Resource": (50000, 80000)
}

job_titles = [
    "Software Engineer", "Data Scientist", "Product Manager", "Web Developer",
    "Systems Analyst", "Marketing Specialist", "HR Generalist", "Finance Analyst",
    "Operations Manager", "Legal Advisor", "Machine Learning Engineer", "Mobile Developer"
]

h1b_pool = []
for country, pct in h1b_country_dist.items():
    count = int(num_employees * 0.4 * pct)
    h1b_pool += [country] * count
h1b_pool += ["USA"] * (num_employees - len(h1b_pool))
random.shuffle(h1b_pool)

data = []
for i in range(num_employees):
    gender = "female" if i % 2 == 0 else "male"
    dept = random.choices(list(department_distribution.keys()), weights=department_distribution.values())[0]
    salary = round(np.random.uniform(*salary_ranges[dept]), 2)
    years_exp = random.randint(0, 30)
    age = random.randint(21, 60)
    languages_spoken = ", ".join(random.sample(languages, random.randint(0, 2)))
    citizenship = h1b_pool[i]
    ssn = fake.ssn()

    record = {
        "First Name": fake.first_name_female() if gender == "female" else fake.first_name_male(),
        "Last Name": fake.last_name(),
        "Email": fake.email(),
        "Phone": fake.phone_number(),
        "Gender": gender,
        "Age": age,
        "Job Title": random.choice(job_titles),
        "Years Of Experience": years_exp,
        "Salary": salary,
        "Department": dept,
        "SSN": ssn,
        "Languages Spoken": languages_spoken,
        "Citizenship": citizenship
    }
    data.append(record)

synth_df = pd.DataFrame(data)

print(synth_df.head(10))

  First Name Last Name                        Email                   Phone  \
0    Natalie   Sanchez       jillrhodes@example.net            296-500-1338
1      Jason      Cole           lisa02@example.net     (254)923-5116x15594
2     Angela    Carter        barbara10@example.net            441.731.6475
3    Michael    Sutton      lynchgeorge@example.net            527.264.8350
4      Debra     Clark          jason76@example.net        724.523.8849x696
5    Brandon  Williams  hernandezernest@example.net     (791)366-9784x80184
6       Jody     Mckay         teresa28@example.org    +1-948-293-2528x8095
7      David     Allen       millertodd@example.org  001-682-827-8248x96383
8    Jessica    Holmes      wrightcaleb@example.org        001-383-293-0103
9       Jose   Ramirez           ilewis@example.net        001-897-737-6311

   Gender  Age           Job Title  Years Of Experience     Salary  \
0  female   31   Software Engineer                    5   94981.60
1    male   41      Data Scientist                   17   59014.29
2  female   24     Systems Analyst                   10   68299.85
3    male   50     Finance Analyst                   20   51973.17
4  female   31     Product Manager                   18   43120.37
5    male   47       Web Developer                   23   86239.78
6  female   39      Data Scientist                   12   57032.93
7    male   38  Operations Manager                    3  114647.05
8  female   51    Mobile Developer                   22   68033.45
9    male   51       Legal Advisor                   17   54161.45

       Department          SSN Languages Spoken Citizenship
0             I/T  655-15-0410                          USA
1  Administrative  734-84-8929                        India
2      Operations  550-16-6202                          USA
3  Administrative  364-27-4375  Tagalog, German         USA
4  Administrative  825-41-6573    German, Hindi       India
5             I/T  142-66-8086  Russian, French         USA
6           Sales  301-56-2592            Hindi         USA
7             I/T  115-47-5039           German         USA
8  Human Resource  688-84-6119    Hindi, Korean       India
9  Administrative  881-43-1161                       Canada

In [ ]:
print(synth_df.describe())

In [9]:
gender_dept_counts = synth_df.groupby(["Department", "Gender"]).size().unstack().fillna(0).astype(int)
print(gender_dept_counts)

Gender          female  male
Department
Administrative     514   495
Finance            238   223
Human Resource     479   487
I/T                462   464
Legal              271   260
Marketing          525   486
Operations        1031  1022
Product            987  1055
Sales              493   508

In [10]:
total_payroll = synth_df["Salary"].sum()
print(f"Total yearly payroll: ${total_payroll:,.2f}")

Total yearly payroll: $802,589,963.95

In [11]:
low_sqft = 10000 * 150
high_sqft = 10000 * 200
print(f"Estimated office space required: {low_sqft:,}–{high_sqft:,} sq ft")

Estimated office space required: 1,500,000–2,000,000 sq ft

In [12]:
pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.11.4)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.0.2)
Collecting htmlmin==0.1.12 (from ydata-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.4.2)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.4)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.5.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.29-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 12.5 MB/s eta 0:00:00
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 16.1 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (687 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 26.7 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.5 MB/s eta 0:00:00
Downloading puremagic-1.29-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 2.8 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=77b5dbc9b7450966e8ccabc354d5ab14f9f7fb3560ce79c89c832c8e3d29b059
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.4 puremagic-1.29 visions-0.8.1 ydata-profiling-4.16.1

In [13]:
from ydata_profiling import ProfileReport

synth_profile = ProfileReport(synth_df, title="Synthetic Employee Data Profile", explorative=True)
synth_profile.to_file("synth_profile.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/13 [00:00<?, ?it/s]
  8%|▊         | 1/13 [00:00<00:01,  9.23it/s]
 23%|██▎       | 3/13 [00:00<00:02,  3.87it/s]
 38%|███▊      | 5/13 [00:00<00:01,  6.12it/s]
 54%|█████▍    | 7/13 [00:00<00:00,  8.56it/s]
 77%|███████▋  | 10/13 [00:01<00:00, 11.95it/s]
100%|██████████| 13/13 [00:01<00:00,  9.65it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
emp_df = pd.read_csv("employees.csv")
emp_profile = ProfileReport(emp_df, title="Original Employee Data Profile", explorative=True)
emp_profile.to_file("original_profile.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]
 30%|███       | 3/10 [00:00<00:00, 22.30it/s]
100%|██████████| 10/10 [00:00<00:00, 34.79it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [17]:
age_weights = synth_df["Age"].apply(lambda age: 3 if 40 <= age <= 49 else 1)

smpl_df = synth_df.sample(n=320, weights=age_weights, random_state=42)


print(smpl_df.describe())

              Age  Years Of Experience         Salary
count  320.000000           320.000000     320.000000
mean    41.921875            14.737500   81944.315344
std      9.624786             8.611422   24930.804769
min     21.000000             0.000000   40008.030000
25%     34.750000             7.000000   59446.592500
50%     44.000000            15.000000   78558.510000
75%     49.000000            22.000000  103446.067500
max     60.000000            30.000000  129933.900000

In [18]:
print(smpl_df.head(10))

     First Name Last Name                       Email                  Phone  \
3749   Jonathon  Mckinney         kgraves@example.org          (791)708-0778
9481      Billy     Price    kentjonathan@example.net           282-748-3869
7292   Kimberly   Farrell  rodriguezduane@example.com     865-980-8800x22200
5938     Pamela    Rivera          todd84@example.com      631-305-6662x4227
1547     Samuel    Nguyen      ginapierce@example.com  001-445-551-3919x6034
571       Larry      Levy          aclark@example.org           319.222.2705
8640      Kelli      Reid     elizabeth56@example.net           419-675-1679
5960      Erica      Kane    wagnertaylor@example.com   +1-248-621-4748x4123
7047     Marvin    Morgan        wolfrita@example.org           491-925-5882
208         Pam      Hall          mike03@example.net      (467)870-0518x449

      Gender  Age                  Job Title  Years Of Experience     Salary  \
3749    male   31  Machine Learning Engineer                    8   57691.74
9481    male   53              Web Developer                    2   57280.58
7292  female   44              Web Developer                    6   58714.55
5938  female   30            Finance Analyst                   18   89559.91
1547    male   30            Systems Analyst                   23  102009.06
571     male   33            Systems Analyst                   24   82427.86
8640  female   49              Legal Advisor                   24  113086.33
5960  female   46          Software Engineer                    7   96014.27
7047    male   50              HR Generalist                    7   90813.64
208   female   21           Mobile Developer                    8   55177.16

          Department          SSN   Languages Spoken Citizenship
3749  Administrative  196-57-1644    Russian, Korean       India
9481      Operations  541-88-4905     Korean, German         USA
7292           Sales  153-98-3007             German       India
5938             I/T  005-27-7440                          India
1547             I/T  191-19-8596  Mandarin, Spanish       China
571            Sales  590-99-9703     Hindi, Spanish         USA
8640             I/T  639-06-7979                          China
5960             I/T  636-62-4302  Mandarin, Russian       China
7047         Product  714-26-5016     Russian, Hindi         USA
208            Sales  368-06-3586            Spanish         USA

In [20]:

fake = Faker()
Faker.seed(123)

anon_df = emp_df.copy()
anon_df["First Name"] = [fake.first_name() for _ in range(len(emp_df))]
anon_df["Last Name"] = [fake.last_name() for _ in range(len(emp_df))]
anon_df["Email"] = [fake.email() for _ in range(len(emp_df))]
anon_df["Phone"] = [fake.phone_number() for _ in range(len(emp_df))]


print(anon_df.describe)

<bound method NDFrame.describe of       First Name Last Name                        Email                Phone  \
0          Brian    Atkins        reedlaura@example.org         695.367.9631
1    Christopher    Arnold     tiffanysmith@example.com         893.441.2066
2        Richard     Smith            fross@example.org  (745)269-5937x27465
3         Daniel     Meyer       isaacperez@example.net   (559)444-6823x1602
4         Rachel   Roberts      hmclaughlin@example.com    359.637.5474x3757
..           ...       ...                          ...                  ...
315       Donald     Banks       meyerssara@example.com  (306)312-9966x03088
316      Jessica  Martinez      charleshall@example.net         229-481-5758
317         Rita      Best  mclaughlinjulia@example.net  +1-281-662-5561x414
318        David     Kelly    adamsmichelle@example.org      +1-673-917-4868
319        Steve   Collins        charles71@example.org   550-355-3041x55718

     Gender  Age                  Job Title  Years Of Experience  Salary  \
0      male   25            Project Manager                    1    8500
1    female   26  Machine Learning Engineer                    2    7000
2      male   37            Project Manager                   14   17000
3    female   31              Web Developer                    8   10000
4      male   35            Project Manager                   11   14500
..      ...  ...                        ...                  ...     ...
315  female   29              Web Developer                    4    9000
316    male   34              Web Developer                   11   11500
317    male   29              Web Developer                    5    8500
318  female   39              Web Developer                   14   13000
319  female   28              Web Developer                    3    8500

    Department
0      Product
1      Product
2      Product
3      Product
4      Product
..         ...
315    Product
316    Product
317    Product
318    Product
319    Product

[320 rows x 10 columns]>

In [21]:
print(anon_df.head(10))

    First Name  Last Name                         Email  \
0        Brian     Atkins         reedlaura@example.org
1  Christopher     Arnold      tiffanysmith@example.com
2      Richard      Smith             fross@example.org
3       Daniel      Meyer        isaacperez@example.net
4       Rachel    Roberts       hmclaughlin@example.com
5     Benjamin      Lewis      howardsharon@example.org
6       Amanda     Zuniga  jonathanschwartz@example.com
7       Martin  Rodriguez        jamesglenn@example.com
8      Melissa   Gallegos          bhickman@example.com
9         Erik    Mullins     perryclifford@example.com

                   Phone  Gender  Age                  Job Title  \
0           695.367.9631    male   25            Project Manager
1           893.441.2066  female   26  Machine Learning Engineer
2    (745)269-5937x27465    male   37            Project Manager
3     (559)444-6823x1602  female   31              Web Developer
4      359.637.5474x3757    male   35            Project Manager
5    +1-819-338-9309x233    male   28            Project Manager
6  001-770-598-8752x4805  female   33  Machine Learning Engineer
7     606-344-5370x94922    male   33           Mobile Developer
8           567-988-5239  female   34              Web Developer
9    +1-309-603-9675x027  female   41              Web Developer

   Years Of Experience  Salary Department
0                    1    8500    Product
1                    2    7000    Product
2                   14   17000    Product
3                    8   10000    Product
4                   11   14500    Product
5                    3   10500    Product
6                   10   11000    Product
7                   10   11000    Product
8                   10   11000    Product
9                   15   14500    Product

In [23]:

prtrb_df = emp_df.copy()

age_std = emp_df["Age"].std() * 0.1
salary_std = emp_df["Salary"].std() * 0.15
exp_std = emp_df["Years Of Experience"].std() * 0.2

np.random.seed(42)
prtrb_df["Age"] = (emp_df["Age"] + np.random.normal(0, age_std, len(emp_df))).round().clip(lower=18)
prtrb_df["Salary"] = (emp_df["Salary"] + np.random.normal(0, salary_std, len(emp_df))).round(2).clip(lower=0)
prtrb_df["Years Of Experience"] = (
    emp_df["Years Of Experience"] + np.random.normal(0, exp_std, len(emp_df))
).round().clip(lower=0)


print(prtrb_df.describe(include='all'))

       First Name Last Name                                 Email  \
count         320       320                                   320
unique        186       237                                   320
top       Michael     Smith  justinwebster303292@slingacademy.com
freq           13         8                                     1
mean          NaN       NaN                                   NaN
std           NaN       NaN                                   NaN
min           NaN       NaN                                   NaN
25%           NaN       NaN                                   NaN
50%           NaN       NaN                                   NaN
75%           NaN       NaN                                   NaN
max           NaN       NaN                                   NaN

                   Phone Gender        Age      Job Title  \
count                320    320  320.00000            320
unique               320      2        NaN              8
top     001-990-293-4626   male        NaN  Web Developer
freq                   1    168        NaN            120
mean                 NaN    NaN   31.57500            NaN
std                  NaN    NaN    4.63265            NaN
min                  NaN    NaN   22.00000            NaN
25%                  NaN    NaN   28.00000            NaN
50%                  NaN    NaN   32.00000            NaN
75%                  NaN    NaN   35.00000            NaN
max                  NaN    NaN   41.00000            NaN

        Years Of Experience        Salary Department
count            320.000000    320.000000        320
unique                  NaN           NaN          2
top                     NaN           NaN    Product
freq                    NaN           NaN        310
mean               7.796875  10166.275656        NaN
std                4.485363   2634.112517        NaN
min                0.000000   5058.450000        NaN
25%                4.000000   8078.302500        NaN
50%                8.000000   9965.790000        NaN
75%               11.000000  12107.502500        NaN
max               16.000000  17108.550000        NaN

In [24]:
print(prtrb_df.head(10))

  First Name Last Name                                 Email  \
0       Jose     Lopez        joselopez0944@slingacademy.com
1      Diane    Carter      dianecarter1228@slingacademy.com
2      Shawn    Foster      shawnfoster2695@slingacademy.com
3     Brenda    Fisher     brendafisher3185@slingacademy.com
4       Sean    Hunter       seanhunter4753@slingacademy.com
5     Joshua    Jacobs     joshuajacobs5904@slingacademy.com
6    Brianna  Marshall  briannamarshall6438@slingacademy.com
7       John      Tate         johntate7881@slingacademy.com
8    Jillian      Byrd      jillianbyrd8170@slingacademy.com
9    Melanie     Sharp     melaniesharp9256@slingacademy.com

                    Phone  Gender   Age                  Job Title  \
0    +1-971-533-4552x1542    male  25.0            Project Manager
1            881.633.0107  female  26.0  Machine Learning Engineer
2    001-966-861-0065x493    male  37.0            Project Manager
3        001-574-564-4648  female  32.0              Web Developer
4              5838355842    male  35.0            Project Manager
5            053-913-2609    male  28.0            Project Manager
6            701-932-8553  female  34.0  Machine Learning Engineer
7  001-889-992-5260x62725    male  33.0           Mobile Developer
8       077-635-0084x1647  female  34.0              Web Developer
9           (848)212-0230  female  41.0              Web Developer

   Years Of Experience    Salary Department
0                  1.0   8538.05    Product
1                  3.0   7233.49    Product
2                 14.0  16678.99    Product
3                  7.0  10820.89    Product
4                 11.0  14105.32    Product
5                  3.0  10023.65    Product
6                  8.0  11454.35    Product
7                 10.0  11310.59    Product
8                 10.0  11244.86    Product
9                 16.0  14746.51    Product